import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router'

import styles from "../styles/Home.module.css";

import PouchDB from "pouchdb";
import PouchDBFind from "pouchdb-find";
import PouchDBUpsert from "pouchdb-upsert";
import PouchDBHelper from "@edgefront/pouchdb-helper";
import { default as _ } from "lodash"
PouchDB.plugin(PouchDBFind);
PouchDB.plugin(PouchDBUpsert);
PouchDB.plugin(PouchDBHelper);
var db = new PouchDB("http://admin:admin@localhost:5984/testdb");

import React, { useState, useEffect } from "react";

// The editor core
import Editor from "@react-page/editor";
// import PageLayout from "../components/PageLayout";

// import the main css, uncomment this: (this is commented in the example because of https://github.com/vercel/next.js/issues/19717)
// import '@react-page/editor/lib/index.css';

// The rich text area plugin
import slate from "@react-page/plugins-slate";
// image
import image from "@react-page/plugins-image";

// Stylesheets for the rich text area plugin
// uncomment this
// import '@react-page/plugins-slate/lib/index.css';

// Stylesheets for the imagea plugin
// import '@react-page/plugins-image/lib/index.css';
// see https://github.com/vercel/next.js/issues/19717  

// Define which plugins we want to use.
const cellPlugins = [slate(), image];

export default function Home() {
  const [value, setValue] = useState(null);
  const [id, setId] = useState(null);
  const [page, setPage] = useState(null);
  const router = useRouter()
  useEffect(() => {
    const {query: {slug}} = router;
    if (slug && slug.length){
      setPage("/" + slug[0]);
    }
    console.log(page)
    db.findOne({
      page
    }).then((doc) => {
      if (doc){
        setId(doc._id);
        setValue(doc.value)
      }else if(!doc && page){
        db.post({
          page
        }).then(status => {
          setId(status.id);
        })
      }
    });
  }, [page,router]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <PageLayout> */}
        <Editor
          cellPlugins={cellPlugins}
          value={value}
          onChange={(v)=>{
            setValue(v);
            _.debounce((v)=>{
              if (page && id && value){
                db.upsert(id, function(doc){
                  doc.value = v;
                  return doc
                })
              }
            }, 1500)(v)
          }
          }
        />
      {/* </PageLayout> */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
