import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import PouchDB from "pouchdb";
import PouchDBFind from "pouchdb-find";
import PouchDBUpsert from "pouchdb-upsert";
import { default as _ } from "lodash"
PouchDB.plugin(PouchDBFind);
PouchDB.plugin(PouchDBUpsert);
var db = new PouchDB("http://admin:admin@localhost:5984/testdb");

import React, { useState, useEffect } from "react";

// The editor core
import Editor from "@react-page/editor";

// import the main css, uncomment this: (this is commented in the example because of https://github.com/vercel/next.js/issues/19717)
// import '@react-page/editor/lib/index.css';

// The rich text area plugin
import slate from "@react-page/plugins-slate";
// image
import image from "@react-page/plugins-image";

import "@react-page/editor/lib/index.css";

// Stylesheets for the rich text area plugin
// uncomment this
//import '@react-page/plugins-slate/lib/index.css';

// Stylesheets for the imagea plugin
//import '@react-page/plugins-image/lib/index.css';

// Define which plugins we want to use.
const cellPlugins = [slate(), image];

export default function Home() {
  const [value, setValue] = useState(null);
  const [id, setId] = useState(null);
  useEffect(() => {
    db.find({
      selector: {
        page: "/index",
      },
    }).then((res) => {
      setId(res.docs[0]._id);
      setValue(res.docs[0].value)
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Editor
        cellPlugins={cellPlugins}
        value={value}
        onChange={
          _.debounce((v)=>{
            console.log(id, value)
            setValue(v);
            if (id && value){
              db.upsert(id, function(doc){
                doc.value = value;
                return doc
              })
            }
          }, 1500)
        }
      />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
